---
- hosts: all
  become: true
  vars: # in yml, if you want to create a variable we need to use vars parameter
   companyName: jerold
   location: chennai
  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: present
  - name: start apache
    service:
      name: httpd
      state: started
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
  - name:    
    systemd: # its a module to enable the service
     name: httpd
     enabled: yes
...      